services:
  mars-mips:
    build: .
    user: "${UID}:${GID}"
    volumes:
      - ./code:/app/code
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
      - USER=${USER}
